# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "src"

[[redirects]]
  from = "/register"
  to = "/index"
  status = 200

[[redirects]]
  from = "/pnf"
  to = "/index"
  status = 200

[[redirects]]
  from = "/pse"
  to = "/index"
  status = 200

[[redirects]]
  from = "/changeProfilePage"
  to = "/index"
  status = 200

[[redirects]]
  from = "/profilePage"
  to = "/index"
  status = 200

[[redirects]]
  from = "/changePassPage"
  to = "/index"
  status = 200

[[redirects]]
  from = "/chatPage"
  to = "/index"
  status = 200
